services:
  - docker:dind

stages:
  - image
  - build
  - package
  - release
  - fdroid

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS: ""
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker-image:
  stage: image
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

.build: &build
  stage: build
  script:
    - bash .ci/build.sh
  artifacts:
    paths:
    - ci-out/

armeabi-v7a:
  <<: *build
  variables:
    TARGET_ARCH: armeabi-v7a

arm64-v8a:
  <<: *build
  variables:
    TARGET_ARCH: arm64-v8a

x86:
  <<: *build
  variables:
    TARGET_ARCH: x86

x86-64:
  <<: *build
  variables:
    TARGET_ARCH: x86_64

package:
  stage: package
  script:
    - ./.ci/package.sh
  only:
    - py3
    - tags
  artifacts:
    paths:
    - package/

release-nightly:
  stage: release
  script:
  - ./.ci/release-nightly.sh
  only:
  - py3
  tags:
  - argon
  artifacts:
    paths:
    - release/

release-production:
  stage: release
  script:
  - ./.ci/download-signed-stable.sh
  only:
  - tags
  except:
  - branches
  when: manual
  artifacts:
    paths:
    - release/

push-to-fdroid:
  stage: fdroid
  script:
  - ./.ci/push-fdroid.sh
